name: Build PastaSync for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: npm install

    - name: Rebuild native modules for macOS ARM64
      run: npx electron-rebuild --arch=arm64

    - name: Build PastaSync App for macOS
      run: npm run build -- --mac --publish=never

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: PastaSync-macOS
        path: dist/
